### ISSUE TITLE
can not install to Anaconda version 2020.02

### ISSUE THREAD

**Issue by sweettyler** [equinor/segyio#465] opened 2020-06-06 14:19 UTC
"conda install -c conda-forge segyio" doesn't work!

you should have received the error report multiple times via conda's report system.

**Comment by JesperDramsch** [comment] 2020-06-06 15:26
I'm currently trying to reproduce the error. Could you share some additional information, as I don't have access to the report system.

So far I'm not able to reproduce any installation error with the information you provided.

**Comment by sweettyler** [comment] 2020-06-06 15:54
@JesperDramsch Thank you for the quick response.
I'll have a fresh installation of Anaconda 2020.02 and then try to reproduce the error. I'll give you the info ASAP.

**Comment by sweettyler** [comment] 2020-06-06 16:05
[pzha@h050017 machineLearning]$ conda install -c conda-forge segyio
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
        return self.__get_result()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

`$ /NFS/ud1/home1/pzha/anaconda3/bin/conda install -c conda-forge segyio`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/NFS/ud1/home1/pzha/anaconda3
                FTP_PROXY=<set>
                  GCCPATH=/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
  INTVIEWER_COLORMAP_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018/ColorMaps
      INTVIEWER_DATA_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
           INTVIEWER_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
      INTVIEWER_WORK_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
          LD_LIBRARY_PATH=/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2/lib64:/prog/sdpsoft/openmpi
                          -1.6.3/lib:/prog/sdpsoft/java-oracle-8/jre/lib/amd64:/wg/common/UTILIT
                          YSUITE/lib:/wg/omega/2018.1ext/linux_64/lib
               MODULEPATH=/wg/omega/2018SDK/2018SDKdev/Modules:/usr/share/Modules/modulefiles:/e
                          tc/modulefiles
                  MPIPATH=/prog/sdpsoft/openmpi-1.6.3
                     PATH=.:/NFS/ud1/home1/pzha/anaconda3/bin:.:/NFS/ud1/home1/pzha/anaconda3/bi
                          n:.:/NFS/ud1/home1/pzha/bin:/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2
                          /bin:/prog/sdpsoft/openmpi-1.6.3/bin:/NFS/ud1/home1/pzha/mytools/SU44/
                          bin:/wg/common/UTILITYSUITE/apps/INTViewer2018/bin:/prog/sdpsoft/git/b
                          in:/wg/omega/2018SDK/2018SDKdev/omni/client/6.9C2183/linux_x86:/usr/lo
                          cal/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/wg/common
                          /UTILITYSUITE/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /NFS/ud1/home1/pzha/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.17
       base environment : /NFS/ud1/home1/pzha/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /NFS/ud1/home1/pzha/anaconda3/pkgs
                          /NFS/ud1/home1/pzha/.conda/pkgs
       envs directories : /NFS/ud1/home1/pzha/anaconda3/envs
                          /NFS/ud1/home1/pzha/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-693.17.1.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 26491:26491
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by sweettyler** [comment] 2020-06-06 16:07
[pzha@h050017 machineLearning]$ conda install -c conda-forge segyio
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
        return self.__get_result()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

`$ /NFS/ud1/home1/pzha/anaconda3/bin/conda install -c conda-forge segyio`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/NFS/ud1/home1/pzha/anaconda3
                FTP_PROXY=<set>
                  GCCPATH=/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
  INTVIEWER_COLORMAP_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018/ColorMaps
      INTVIEWER_DATA_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
           INTVIEWER_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
      INTVIEWER_WORK_PATH=/wg/common/UTILITYSUITE/apps/INTViewer2018
          LD_LIBRARY_PATH=/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2/lib64:/prog/sdpsoft/openmpi
                          -1.6.3/lib:/prog/sdpsoft/java-oracle-8/jre/lib/amd64:/wg/common/UTILIT
                          YSUITE/lib:/wg/omega/2018.1ext/linux_64/lib
               MODULEPATH=/wg/omega/2018SDK/2018SDKdev/Modules:/usr/share/Modules/modulefiles:/e
                          tc/modulefiles
                  MPIPATH=/prog/sdpsoft/openmpi-1.6.3
                     PATH=.:/NFS/ud1/home1/pzha/anaconda3/bin:.:/NFS/ud1/home1/pzha/anaconda3/bi
                          n:.:/NFS/ud1/home1/pzha/bin:/wg/omega/2018SDK/2018SDKdev/EL6/gcc-4.9.2
                          /bin:/prog/sdpsoft/openmpi-1.6.3/bin:/NFS/ud1/home1/pzha/mytools/SU44/
                          bin:/wg/common/UTILITYSUITE/apps/INTViewer2018/bin:/prog/sdpsoft/git/b
                          in:/wg/omega/2018SDK/2018SDKdev/omni/client/6.9C2183/linux_x86:/usr/lo
                          cal/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/wg/common
                          /UTILITYSUITE/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /NFS/ud1/home1/pzha/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.17
       base environment : /NFS/ud1/home1/pzha/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /NFS/ud1/home1/pzha/anaconda3/pkgs
                          /NFS/ud1/home1/pzha/.conda/pkgs
       envs directories : /NFS/ud1/home1/pzha/anaconda3/envs
                          /NFS/ud1/home1/pzha/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-693.17.1.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 26491:26491
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by sweettyler** [comment] 2020-06-06 16:11
above is the error message. Before installing segyio, I did the following to freshly install Anaconda 2020.02:
  1) rm -rf ~/.anaconda
  2) rm -rf ~/.conda
  3) rm -rf ~/.condarc
  4) rm -rf ~/anaconda3
  5) ./Anaconda3-2020.02-Linux-x86_64.sh

**Comment by jokva** [comment] 2020-06-06 16:20
```
  File "/NFS/ud1/home1/pzha/anaconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 420, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None
```
Looks like there's nothing wrong with the package, but with your network settings. Do other packages work?

**Comment by JesperDramsch** [comment] 2020-06-06 16:56
Your environment variables for proxies are set but not filled. This leads to uncaught exceptions in Python 3.7.6 and as far as I'm aware they're working on a fix.

This is not an issue with segyio but with [conda](https://github.com/conda/conda/issues/9662) or rather Python itself having hicc-ups with your system configuration. Is there a reason to have those env variables exist without values?

It's possible this is the reason, why the report uploads to the conda system also failed, because they supposedly also rely on the proxy settings.

**Comment by sweettyler** [comment] 2020-06-06 19:57
I agree there must be something wrong, but probably not what you have pointed out.

I also tried many times that I freshly installed Anaconda 2019.10 first and then installed segyio - in this case I had no problem at all. From my point of view, the environment were same and I exactly repeated the same procedure of installation (please refer the list of commands in my previous post).

I am not sure if you tried to reproduce the issue on your own computer, did you succeed?

Thank you for your time.

**Comment by sweettyler** [comment] 2020-06-06 20:06
I saw the last code update of segyio was 5 months ago. Anaconda 2020.02 was release in April 2020. I think maybe segyio need to make some changes to adapt to the new Anaconda.

**Comment by sweettyler** [comment] 2020-06-06 20:42
The following is the installation of segyio on Anaconda 2019.10:
=====================================================================
[pzha@h050017 machineLearning]$ conda install -c conda-forge segyio
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /NFS/ud1/home1/pzha/anaconda3

  added / updated specs:
    - segyio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |   py37hc8dfbb8_1         3.0 MB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    segyio-1.9.0               |   py37hb3f55d8_0         140 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  segyio             conda-forge/linux-64::segyio-1.9.0-py37hb3f55d8_0

The following packages will be UPDATED:

  conda                      pkgs/main::conda-4.7.12-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
segyio-1.9.0         | 140 KB    | ##################################################################### | 100% 
conda-4.8.3          | 3.0 MB    | ##################################################################### | 100% 
python_abi-3.7       | 4 KB      | ##################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[pzha@h050017 machineLearning]$

**Comment by jokva** [comment] 2020-06-09 11:52
In your first outputs, you don't even get to the point where you're fetching segyio. I don't believe this is an issue with the package (and Jesper was unable to reproduce), but rather with the setup of your system.

**Comment by sweettyler** [comment] 2020-06-09 13:15
Thank you all for your time and help.
Just googled and found it was caused by some changes in Anaconda 2020.02.

**Comment by jokva** [comment] 2020-06-09 21:22
Alright, then I'm closing this issue.

**Closed by jokva** 2020-06-09 21:22 UTC
